### ISSUE TITLE
32x32 Pixel Tile Size

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#3]
Do either of you see a problem with switching to just support only a map tile size of 32 by 32? It will make logic supporting map movement, positions, mouse coordinates much simpler. In my opinion high benefit for little cost as their is no reason I can think of that we would need maps with different tile sizes.

**Comment by bxs9775** [comment]
We will problably use all 32 by 32 size tiled maps, though we may want to be able to change the size if we get to the resolution adjustment stretch goal. I would leave it for now because it would take less work to change the size of the tiles under the current system and we may change our minds about how big a map tile should be.

**Comment by CScavone96** [comment]
I think I hardcoded some stuff as 32 but Ill try and fetch map and pull tile variables instead from now on.
